-- Supabase/PostgreSQL schema for application users.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text,
  email text,
  google_subject text,
  display_name text,
  created_at timestamptz default now()
);

create unique index if not exists users_google_subject_key
  on public.users (google_subject)
  where google_subject is not null;

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null default '',
  ingredients text not null default '',
  instructions text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recipes_user_id_idx on public.recipes (user_id);
