-- Supabase/PostgreSQL schema for application users.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text,
  email text,
  google_subject text,
  display_name text,
  created_at timestamptz default now()
);

create unique index if not exists users_google_subject_key
  on public.users (google_subject)
  where google_subject is not null;
